Be review
codesquad-member-2020/todo-5 pull request #120
Opened 2020-04-17 08:51 UTC by jypthemiracle

2020-04-18 04:40 UTC, wheejuni requested changes
수고 많으셨습니다.
아래 코멘트가 도움되었으면 좋겠습니다.

그리고 `gitignore` 처리가 제대로 안 된거 같은데 한번만 확인해 주시고요.

2020-04-18 04:40 UTC, wheejuni commented on BE/build/resources/main/application.properties
> +spring.datasource.password=codesquad
다음부터는 password 형상관리 되지 않는 방법 고민해 주세요.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/config/FilterConfig.java
> +{
bracket 컨벤션 지켜 주세요. 
클래스 이름 바로 옆에서 여는게 원칙입니다.

```java
@Configuration
public class FilterConfig {
...
```

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/config/FilterConfig.java
> +  {
여기도요.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/config/WebMvcConfigurerImpl.java
> +    registry.addInterceptor(new HttpInterceptor(jwtService))
`HttpInterceptor` 를 bean으로 주입받아서 사용하는 방법을 택해 주시고요, 
MVC Configuration에서 service layer에 의존성 갖지 않게 수정해주세요.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/controller/TaskController.java
>      response.setStatus(true);
static method 하나 만들어서 OK status를 위한 response 만들어주는 방법 고민해 보세요.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/controller/CategoryController.java
> +    //response.setStatus(true);
불필요한 주석은 날려버립시다.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/controller/UserController.java
> +  @GetMapping("/user/auth")
로그인의 기능이라면 사실 Filter나 Interceptor에서 구현되는 것이 맞기는 합니다.
다음엔 고민해주세요.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/domain/activity/Activity.java
> +//  TODO 이거 서버에서 해줘야 하는데 DEFAULT current_timestamp 선언 해줬는데 NULL로 찍혀서 임시방편 처리하였음
진짜 TODO라면 `//TODO` 와 같이 시작하여 IDE의 todo-list로 관리될 수 있게 하는 것이 바람직합니다.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/domain/activity/ActivityRepository.java
> +  Optional<List<Activity>> findAllActivity();
`List` 에서 `Optional` 을 굳이 사용할 필요는 없고,
어차피 결과값이 없다면 빈 리스트가 반환될 겁니다.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/domain/activity/Target.java
> +  public String getAction() {
`enum` 에서도 `@Getter` 사용해도 됩니다.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/domain/category/CategoryRepository.java
> +  Long lastInsertId();
`AUTO_INCREMENT` 로 안된 모양이죠?

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/dto/category/CategoryWithTasksDto.java
> +    this.task = category.getTask().stream()
`category` 객체에 null이라도 들어간다치면 이 DTO도 다 `null` 필드를 갖게 되겠군요. 
생성자는 field의 자료형을 그대로 반영하고, `Category` 객체에 대해서 변환이 필요하다면 `.fromEntity()` 와 같은 스태틱 메소드를 만들어서 변환하는 방법을 추천해보고 싶긴 한데요.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/exception/InvalidInputException.java
> +    public InvalidInputException() { super("입력한 정보가 일치하지 않습니다. 다시 입력 해주세요."); }
bracket 연 후에 개행 한번 해주세요. 

```java
public InvalidInputException() {
    super(...)
}
```

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/service/JwtService.java
> +    private Logger logger = LoggerFactory.getLogger(JwtService.class);
이젠 로거도 `@Slf4j` 로 처리하셔도 될 듯 합니다.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/service/UserService.java
>      //TODO 왜 위에서는 List<Activity>라고 선언해주었는데도 orElseThrow의 선언이 가능하지? activityRepository는 Optional로 선언하지 않았을 때는 orElseThrow의 선언이 불가능했던 것을 생각해보자.
무슨 말이죠

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/utils/JsonUtils.java
> +  public JSONObject readJSONStringFromRequestBody(HttpServletRequest request){
이 메소드 static으로 바꾸고 아래 `StringBuffer` 를 `StringBuilder` 로 바꿔주세요.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/utils/JsonUtils.java
> +  public JsonUtils() {
오히려 `private` 으로 막아서 instantiation을 막아야 할 클래스로 보여지는데요.

2020-04-18 04:40 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/utils/JsonUtils.java
> +      System.out.println(e);
sysout 하지 마세요.

2020-04-18 06:53 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/todo5/dto/category/CategoryWithTasksDto.java
> +    this.task = category.getTask().stream()
이런 것일까요?

TasksService 객체:
```
@Transactional
    public Long save(TasksSaveRequestDto requestDto) {
        return tasksRepository.save(requestDto.toEntity());
    }
````

Tasks 객체:
```
public Tasks toEntity() {
        return Posts.create(title, content, author);
    }
```

2020-04-18 07:05 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/todo5/config/WebMvcConfigurerImpl.java
> +    registry.addInterceptor(new HttpInterceptor(jwtService))
생성자 주입이 아니라 ```@Autowired``` 를 활용하라는 말씀이실까요?

2020-04-18 10:51 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo5/config/WebMvcConfigurerImpl.java
> +    registry.addInterceptor(new HttpInterceptor(jwtService))
`new` 를 사용하셨기 때문에 주입하신 게 아니십니다. 
Application Context로 관리되는 객체가 아닌 게 돼요. 

생성자 주입을 사용하지 말라는 것이 아니라, `@Configuration` 클래스 등에서 생성자 주입을 통해 등록한 bean을 이 Configurer에서 다시 주입받아 사용하시라고 권해 드리는 것입니다.

2020-04-18 12:05 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/todo5/config/WebMvcConfigurerImpl.java
> +    registry.addInterceptor(new HttpInterceptor(jwtService))
아 이해했습니다. HttpInterceptor에 @Component 또는 @Configuration과 @Bean 선언을 활용하여 ApplicationContext에 등록한 후 이를 주입받으라는 말씀으로 이해하면 될까요?

2020-05-06 08:48 UTC, honux77 commented on BE/src/main/java/com/codesquad/todo5/config/FilterConfig.java
> +{
@jypthemiracle 코딩 컨벤션은 꼭 지켜주세요. 사소하더라도~

2020-05-06 08:51 UTC, merged